version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./front/dockerfile
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"